---
driver:
  name: dokken
  chef_version: latest
  volumes:
  # saves the apt archieves outside of the container
  - /var/cache/apt/archives/:/var/cache/apt/archives/

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: ubuntu-18.04
  driver:
    image: dokken/ubuntu-18.04
    intermediate_instructions:
    - RUN rm /etc/apt/apt.conf.d/docker-clean
    - RUN /usr/bin/apt-get update

suites:
  - name: default
    run_list: [ "recipe[auto-updater::default]" ]
    verifier:
      inspec_tests: [ "test/smoke/default" ]
    attributes:
      'auto-updater':
        update:
          last_update_at: 0

  - name: recently_updated
    run_list: [ "recipe[auto-updater::update]" ]
    verifier:
      inspe c_tests: [ "test/smoke/update" ]
    attributes:
      'auto-updater':
        update:
          last_update_at: <%= Time.now.to_i - 36 * 3600 %>

  - name: timezone
    run_list: [ "recipe[auto-updater::timezone]" ]
    verifier:
      inspe c_tests: [ "test/smoke/timezone" ]
    attributes:
      'auto-updater':
        update:
          last_update_at: <%= Time.now.to_i - 36 * 3600 %>
